### ISSUE TITLE
Integration tests are not running

### ISSUE THREAD

**Issue by sw-tracker** [odrotbohm/arch-evident-spring#1]
Hi there,

I am using your repository as an example on how to write tests, but when I checkout the main branch, the `OrderIntegrationTests` integration tests dont run.

I am getting the following error: `Error creating bean with name 'orderRepository' defined in example.order.OrderRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Not a managed type: class example.order.Order`.

Thanks!

**Comment by odrotbohm** [comment]
You have to make sure that the ByteBuddy plugin is running after compilation. If you use IDEA, you need to explicitly enable that. I've documented the necessary steps [here](https://github.com/xmolecules/jmolecules-integrations/tree/main/jmolecules-bytebuddy#quickstart). The ticket asking to get this done automatically is [here](https://youtrack.jetbrains.com/issue/IDEA-199681).
