### ISSUE TITLE
about jmolecules libraries used in this project

### ISSUE THREAD

**Issue by doxxx93** [odrotbohm/arch-evident-spring#2]
is there correlation with spring modulith?

Or just your recomendation to use it?

**Comment by odrotbohm** [comment]
We use jMolecules here to extend on the idea of architecturally evident code in the first place. It allows avoiding unnecessary default JPA mappings by expressing the `Order`'s aggregate nature using jMolecules. That information is then translated into the boilerplate JPA metadata using ByteBuddy.

Spring Modulith supports it by grouping the Spring beans documented in the application module canvas according to the jMolecules architecture annotations you might have chosen, and detects application events if the abstractions in `jmolecules-events` are used. So the two libraries nicely complement each other but Spring Modulith also generally works without jMolecules.
