### ISSUE TITLE
As this the latest and greatest spring lib - Modulith, consider using gradle kotlin DSL

### ISSUE THREAD

**Issue by nagkumar** [odrotbohm/arch-evident-spring#3]
As this the latest and greatest spring lib - Modulith, consider using gradle kotlin DSL even in examples

**Comment by odrotbohm** [comment]
I am not deeply familiar with Gradle builds, and the project is not a showcase for general usage. Hence, I'm not going add that as it would create effort to maintain that I don't think I will want to live with.
