### ISSUE TITLE
Test passes when it shouldn't (steps/0)

### ISSUE THREAD

**Issue by mikybars** [odrotbohm/arch-evident-spring#6]
In the docs you can read: 

> Run `OrderIntegrationTests` — The tests fails as the bean reference to Inventory cannot be satisfied

That's not my case. Anyone else is having the same issue?

**Comment by odrotbohm** [comment]
That statement depends on the introduction of a dependency between `OrderManagement` and `Inventory` in Step 0 / A (second bullet point).

**Comment by mikybars** [comment]
![image](https://github.com/odrotbohm/arch-evident-spring/assets/43891734/ad38d541-d4f2-4fc6-ab9e-24a593ae0177)

**Comment by mikybars** [comment]
Oh I think this was my mistake. I was running the tests through IntelliJ and for some reason they didn't fail. I ran them again with Maven and this time they did fail. I guess there's some extra step in the compilation that's not being taken into account by IntelliJ. Can it be the byte-buddy transform from jMolecules?

**Comment by odrotbohm** [comment]
It likely is, I've just added [a hint](https://github.com/xmolecules/jmolecules-integrations/tree/main/jmolecules-bytebuddy#quickstart) about how to get this working to the readme of the Bytebuddy module (the `IMPORTANT` block).

**Comment by mikybars** [comment]
I appreciate it. It works like a charm now ❤️  Nothing more reassuring than seeing a test fail when it should.

**Comment by odrotbohm** [comment]
Glad you got it working. Happy coding! 🥳
